# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "actions" ]
  pull_request:
    branches: [ "main", "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [vookimedlo/ubuntu-clang:clang_bionic]
        
    runs-on: ${{ matrix.os }}
    env:
      app_name: app_${{ matrix.os }}_${{ github.run_number }}
    steps:
      - uses: actions/checkout@v3
      - name: Show folder
        run: ls
      - name: Show pwd
        run: pwd
        
#       - name: Install aptitude
#         run: sudo apt install aptitude -y
#       - name: Install QT
#         run: sudo aptitude install qt5-qmake -y
      - name: Update apt-get
        run: sudo apt-get update -qq
        
      - name: Install QT
        run: apt-get -y install qt5-default qt5-image-formats-plugins

#       - name: Run qmake build
#         run: qmake -makefile -qtconf "CChat.pro"
      
      - name: Show server
        working-directory: ./server
        run: ls
      - name: Run qmake build
        working-directory: ./server
        run: qmake -makefile

      

      - name: Show client
        working-directory: ./client
        run: ls
      - name: Run qmake build
        working-directory: ./client
        run: qmake -makefile
        
      # - name: Build
      #   run: g++ hello.cpp -o ${{ env.app_name }}
      # - name: 'Upload Artifact'
      #   uses: actions/upload-artifact@v3
      #   with: 
      #     name: my-artifact-matrix
      #     path: ${{ env.app_name }}*
      #     retention-days: 5 

          
          
      
    
        
        
        
