# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "actions" ]
  pull_request:
    branches: [ "main", "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_matrix:
    strategy:
      matrix:
        os: [ubuntu-20.04]
        
    runs-on: ${{ matrix.os }}
    env:
      app_name: app_${{ matrix.os }}_${{ github.run_number }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Show folder
        run: ls
      - name: Show bin
        run: ls $GITHUB_WORKSPACE/..
        
      - name: Update apt-get
        run: sudo apt-get update -qq
        
      - name: Install QT
        run: sudo apt-get -y install qt5-default qt5-image-formats-plugins
      
      - name: Show server
        working-directory: ./server
        run: ls
      - name: Run qmake build
        working-directory: ./server
        run: qmake -makefile "DESTDIR=$GITHUB_WORKSPACE"
      - name: Run make
        working-directory: ./server
        run: make -o "run_server"
      - name: Show server
        working-directory: ./server
        run: ls
      

      - name: Show client
        working-directory: ./client
        run: ls
      - name: Run qmake build
        working-directory: ./client
        run: qmake -makefile "DESTDIR=$GITHUB_WORKSPACE"
      - name: Run make
        working-directory: ./client
        run: make -o "run_client"
      - name: Show client
        working-directory: ./client
        run: ls

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with: 
          name: Chat-artifacts
          path: | 
            $GITHUB_WORKSPACE/server
            $GITHUB_WORKSPACE/client
          retention-days: 5 

          
          
      
    
        
        
        
